[[redirects]]
  from = "/"
  to = "https://greasyfork.org.cn/"
  status = 308
  force = true

[[redirects]]
  from = "/404"
  to = "https://thepage-gfork.zh-hk.eu.org/404"
  status = 200
  force = true

[[redirects]]
  from = "/redirect/to"
  to = "https://thepage-gfork.zh-hk.eu.org/redirect/to"
  status = 308
  force = true

[[redirects]]
  from = "/redirect/"
  to = "https://thepage-gfork.zh-hk.eu.org/redirect/"
  status = 308
  force = true

[[redirects]]
  from = "/*"
  to = "https://greasyfork.org.cn/:splat"
  status = 308
  force = true